Fixed global config creation for /etc/scduply

diff --git a/scduply b/scduply
--- a/scduply
+++ b/scduply
@@ -159,9 +159,9 @@ function write_config {
   local CONFDIR="$1"
   local CONF="$2"
 
-  if [ ! -d "$CONFDIR" ] ; then
-    mkdir -p "$CONFDIR" || error "Couldn't create config '$CONFDIR'."
+  mkdir -p "$CONFDIR" || error "Couldn't create config '$CONFDIR'."
   # create initial config file
+  if [ ! -f "$CONF" ] ; then
     cat <<EOF >"$CONF"
 # gpg key data (for symmetric encryption comment out GPG_KEY), examples:
 #  GPG_KEY='disabled' - disables encryption alltogether
@@ -271,10 +271,8 @@ function create_config {
     # Hints on first usage
     cat <<EOF
 
-The main profile '$CONFHOME' has been created.
-The global config file has been created as 
-'$MAINCONF'.
-You should now adjust this config file to your needs.
+*** The scduply initialized in '$CONFHOME'.
+The initial global config file is '$MAINCONF'.
 
 EOF
   fi
@@ -284,10 +282,10 @@ EOF
   # Hints on first usage
   cat <<EOF
 
-Congratulations. You just created the profile '$FTPLCFG'.
-The initial config file has been created as 
-'$CONF'.
-You should now adjust this config file to your needs.
+*** Created profile '$FTPLCFG'.
+The backup source path is '$SRCHOLDER'.
+The exclude globing list is '$EXCLUDE'.
+The initial config file is '$CONF'.
 
 $(hint_profile)
 
@@ -299,6 +297,7 @@ EOF
 function hint_profile {
   cat <<EOF
 IMPORTANT:
+  The profile folder is '$CONFDIR'.
   Copy the _whole_ profile folder after the first backup to a safe place.
   It contains everything needed to restore your backups. You will need 
   it if you have to restore the backup from another system (e.g. after a 
